### ISSUE TITLE
Problem with Custom AnimatedSink

### ISSUE THREAD

**Issue by vander2675** [RxSwiftCommunity/RxAnimated#13]
While trying to add an AnimatedSink for UIEdgeInsets for an CollectionView. Compiler is complaining that ```self.type``` and ```self.base```are inaccessibble due to internal protection level.
Why are they specifically marked internal?

```
extension AnimatedSink where Base: UICollectionView {
    var contentInsets: Binder<UIEdgeInsets> {
        let animation = self.type
        return Binder(self.base) { collectionView, insets in
            self.type.animate(view: collectionView, binding: {
                guard let collectionView = collectionView as? UICollectionView else { return }
                collectionView.contentInsets = insets
            })
        }
    }
}
```

**Comment by icanzilb** [comment]
I got to try this - it's probably a mistake. Did you manage to add the new sink when you changed the access level? Maybe send a PR

**Comment by vander2675** [comment]
Yep it worked. I will send a PR.

**Comment by icanzilb** [comment]
awesome, thanks @vander2675 !

**Comment by icanzilb** [comment]
merged
