### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by Pwyll28** [RxSwiftCommunity/RxAnimated#6]
Are you going to support Carthage ?

**Comment by icanzilb** [comment]
if there is a committed community member who's willing to add and maintain Carthage support I'll help with what I can.

**Comment by IgorBulyga** [comment]
#7

**Comment by agordeev** [comment]
Still no Carthage support?

**Comment by mickamy** [comment]
Now we have Carthage support on v0.8.1.

https://github.com/RxSwiftCommunity/RxAnimated/pull/37
https://github.com/RxSwiftCommunity/RxAnimated/releases/tag/0.8.1
